### ISSUE TITLE
stack_snapshot ignores stack warning about missing Cabal file in archive overrides

### ISSUE THREAD

**Issue by aherrmann** [tweag/rules_haskell#1762]
**Describe the bug**
Using a local snapshot to point to an archive URL or specific Github commit/fork will silently ignore the override and still use the Hackage version of the underlying resolver if the new archive does not include a Cabal file.

Specifically, `stack ls dependencies json --global-hints --external` will print out a warning of the form
```
DEPRECATED: The package at Archive from https://github.com/fpco/unliftio/archive/de13c448e4b77e8ce318b78445e17f6c20003325.tar.gz in subdir unliftio does not include a cabal file.
Instead, it includes an hpack package.yaml file for generating a cabal file.
This usage is deprecated; please see https://github.com/commercialhaskell/stack/issues/5210.
Support for this workflow will be removed in the future.
```
But, it will still return exit code 0 and ignore the archive override and `stack_snapshot` does not notice that something went wrong.

**To Reproduce**
1. Use a local Stackage snapshot of the form
    ```
    resolver: nightly-2022-06-10
    packages:
      - github: "fpco/unliftio"
        commit: de13c448e4b77e8ce318b78445e17f6c20003325
        subdirs:
          - unliftio-core
          - unliftio
    ```
    and add `unliftio-core` to the `packages` attribute of `stack_snapshot`.
2. Repin the snapshot repository.
3. Inspect the generated lock-file and observe that `unliftio-core` is still fetched from Hackage instead of Github at commit de13c448.

**Expected behavior**
If `stack` cannot provide the requested override in a custom snapshot, then `stack_snapshot` fetch/pin should fail with a clear error message, instead of silently ignoring the issue.

**Environment**
 - OS name + version: Ubuntu 21.10
 - Bazel version: 4.2.1
 - Version of the rules: b8ac6c18d26c0011a2464200762e45302a70bbf6

**Additional context**
https://github.com/commercialhaskell/stack/issues/5210 points out that repositories should contain a Cabal file.
